name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@main
      with:
          submodules: 'recursive'
          
    - name: Configure CMake and Build
      run:    |
               wget https://dl.google.com/android/repository/android-ndk-r25-linux.zip 
               unzip android-ndk-r25-linux.zip
               android_ci_build.bash

    - name: Upload build output
      uses: actions/upload-artifact@main
      with:
        name: native
        path: build/*.so
